apiVersion: 1

datasources:
  - name: MetricsPostgres
    type: postgres
    access: proxy
    url: metrics-postgres:5432
    user: benchmark
    jsonData:
      database: benchmarks
      sslmode: disable
    secureJsonData:
      password: benchmark
    isDefault: true
